# Generated by Django 6.0.2 on 2026-03-08 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trackingNumber", models.CharField(max_length=15, unique=True)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "currentStatus",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En tránsito", "En tránsito"),
                            ("Entregada", "Entregada"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GuideHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En tránsito", "En tránsito"),
                            ("Entregada", "Entregada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("updatedBy", models.CharField(max_length=20)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="guides.guide",
                    ),
                ),
            ],
        ),
    ]
