# Generated by Django 6.0.2 on 2026-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_alter_guidehistory_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="client",
            field=models.CharField(max_length=100),
        ),
    ]
