# Generated by Django 6.0.2 on 2026-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0004_alter_guide_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidehistory",
            name="updatedBy",
            field=models.CharField(max_length=10),
        ),
    ]
