# Generated by Django 6.0.2 on 2026-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0005_alter_guidehistory_updatedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="trackingNumber",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
